"""deleted phone

Revision ID: ac5f0022c76d
Revises: 71cafe11ef11
Create Date: 2026-04-16 18:19:27.706858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac5f0022c76d'
down_revision: Union[str, Sequence[str], None] = '71cafe11ef11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
